# Generated by Django 6.0.6 on 2026-06-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='total_chunks',
            field=models.IntegerField(default=0),
        ),
    ]
