# Generated by Django 6.0.6 on 2026-06-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0002_document_total_chunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='total_chunks',
            field=models.IntegerField(),
        ),
    ]
