# Generated by Django 6.0.6 on 2026-06-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0003_document_processing_time_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='duplicate_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='language',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='quality_score',
            field=models.FloatField(default=0),
        ),
    ]
