# Generated by Django 6.0.6 on 2026-06-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0004_document_duplicate_chunks_document_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='processing_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(default='COMPLETED', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='total_chunks',
            field=models.IntegerField(default=0),
        ),
    ]
