# Generated by Django 6.0.6 on 2026-06-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0005_alter_document_processing_time_alter_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='complexity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='COMPLETED', max_length=50),
        ),
    ]
